### Nested Loop

In [50]:
num = int(input("Enter your number: "))

# Handle special cases first
if num < 2:
    print("The number is neither prime nor composite")
else:
    # Assume the number is prime until proven otherwise
    is_prime = True
    
    # Check divisibility starting from 2 up to the square root of num
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    
    # Output the result based on the flag
    if is_prime:
        print("The number is prime")
    else:
        print("The number is composite")

Enter your number:  0


The number is neither prime nor composite


In [63]:
for i in range(1,10):
    print("The table of {}".format(i))
    for j in range(1,11):
        print("{} X {} = {}".format(i,j,i*j))
    print()

The table of 1
1 X 1 = 1
1 X 2 = 2
1 X 3 = 3
1 X 4 = 4
1 X 5 = 5
1 X 6 = 6
1 X 7 = 7
1 X 8 = 8
1 X 9 = 9
1 X 10 = 10

The table of 2
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20

The table of 3
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30

The table of 4
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
4 X 10 = 40

The table of 5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50

The table of 6
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
6 X 10 = 60

The table of 7
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
7 X 10 = 70

The table of 8
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
8 X 10 = 80

The ta

### Break

In [68]:
list = [x for x in range(1,100) if x % 3 == 0]

In [72]:
for i in range(1,100):
    if i == 20:
        continue
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [100]:
for i in range(1,100):
    if i == 20:
        break         # Breaks the code once the objective is achieved
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### continue

In [102]:
for i in list:
    if i % 5 == 0 or i % 7 == 0:
        continue # It's skips the i's whic follow the condition mentioned
    print(i)

3
6
9
12
18
24
27
33
36
39
48
51
54
57
66
69
72
78
81
87
93
96
99


### Pass

In [104]:
for i in range(1,100):
    for j in range(1,50):
        pass           # Implements the logic later
print("The code is incomplete")

The code is incomplete


### Def function

In [109]:
def sumproduct(a,b):
    return 2*a + 3*b

sumproduct(7,9)

41

In [111]:
def sumSquares(a,b):
    return a**2 + b**2

sumSquares(9,3)

90

In [113]:
def sumSquares(a,b):
    x = a**2
    y = b**2
    z = x * y
    return z

sumSquares(7,2)

196

In [115]:
def display():
    print("This is the def display() function")

In [117]:
display()

This is the def display() function


In [119]:
# Numpy
# Pandas
# Matplotlib
# Seaborn
# Scipy
# Sklearn

### Numpy

In [128]:
# pip install numpy
import numpy as np 

In [130]:
arr = np.array([x for x in range(1,6)])

In [132]:
print(arr)

[1 2 3 4 5]


#### create arrays

In [135]:
arr

array([1, 2, 3, 4, 5])

In [143]:
a = np.array([[x for x in range(1,4)],[7,8,9]]) 

In [145]:
print(a)

[[1 2 3]
 [7 8 9]]


In [147]:
b = np.zeros((2,3))

In [151]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [153]:
ones = np.ones((3,3))

In [155]:
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [159]:
consecutive = np.arange(11)

In [161]:
consecutive

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
a.shape

(2, 3)

In [165]:
b.shape

(2, 3)

In [167]:
ones.shape

(3, 3)

In [169]:
consecutive.shape

(11,)

In [171]:
ones.ndim

2

In [173]:
ones.size

9

In [175]:
ones.dtype

dtype('float64')

In [177]:
d = np.array([[1,2],[3,4],[5,6],[7,8]])

In [179]:
d.shape

(4, 2)

In [181]:
d.ndim

2

In [183]:
d.size

8

In [185]:
e = np.array([1,2,3,4,5,6,7,8])

In [187]:
e.shape

(8,)

In [189]:
e.size

8

In [191]:
e.ndim

1

In [193]:
a

array([[1, 2, 3],
       [7, 8, 9]])

In [195]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [197]:
d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [205]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [207]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [209]:
y

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [211]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [215]:
print(y)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [217]:
print(y-x)

[[ 9 18 27]
 [36 45 54]
 [63 72 81]]


In [219]:
print(x*y)
print()
print(y/x)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [221]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [223]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [227]:
e.shape

(8,)

In [229]:
angles = np.array([[30,45,],[60,90],[120,180]])

In [231]:
angles

array([[ 30,  45],
       [ 60,  90],
       [120, 180]])

In [233]:
np.sin(angles)

array([[-0.98803162,  0.85090352],
       [-0.30481062,  0.89399666],
       [ 0.58061118, -0.80115264]])

In [237]:
np.cos(angles)

array([[ 0.15425145,  0.52532199],
       [-0.95241298, -0.44807362],
       [ 0.81418097, -0.59846007]])

In [239]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.94591015, 2.07944154, 2.19722458]])

In [241]:
a

array([[1, 2, 3],
       [7, 8, 9]])

#### Indexing and Slicing

In [250]:
angles[1,1]

90

In [252]:
angles

array([[ 30,  45],
       [ 60,  90],
       [120, 180]])

In [254]:
angles[2,1]

180

In [260]:
bigger = np.array([[x for x in range(1,6)],[x for x in range(6,11)],[x for x in range(11,16)],[x for x in range(16,21)],[x for x in range(21,26)]])

In [262]:
bigger

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [268]:
bigger[0:3,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [274]:
bigger[2:5,1:3]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [276]:
bigger[:,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [278]:
bigger[:,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [280]:
bigger[1:3,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])